server:
  port: 9009
spring:
  application:
    name: tensquare_sms

  rabbitmq:
    host: 192.168.88.128
aliyun:
  sms:
    accessKeyId: LTAIKwFq9lPHwLvh
    accessKeySecret: 不告诉你
    template_code: SMS_149385475
    sign_name: 传智播客